package org.alterq.util.enumeration;

public enum MessageResourcesNameEnum {
	USER_NOT_VALIDATE("USER_NOT_VALIDATE"),
	USER_NOT_IN_SESSION("USER_NOT_IN_SESSION"),
	USER_NOT_EXIST("USER_NOT_EXIST"),
	USER_ALREADY_EXIST("USER_ALREADY_EXIST"),
	USER_NOT_SAME("USER_NOT_SAME"),
	USER_NOT_ADMIN("USER_NOT_ADMIN"),
	USER_NULL("USER_NULL"),
	GET_LAST_ROUND("GET_LAST_ROUND"),
	USER_NOT_MONEY_ENOUGH("USER_NOT_MONEY_ENOUGH"),
	USER_NAME_ERROR("USER_NAME_ERROR"),
	USER_NAME_LENGTH("USER_NAME_LENGTH"),
	USER_PHONE_ERROR("USER_PHONE_ERROR"),
	USER_PHONE_NUMERIC("USER_PHONE_NUMERIC"),
	USER_PHONE_LENGTH("USER_PHONE_LENGTH"),
	USER_MAIL_ERROR("USER_MAIL_ERROR"),
	USER_AUTOMATIC_ERROR("USER_AUTOMATIC_ERROR"),
	USER_NIF_ERROR("USER_NIF_ERROR"),
	USER_PASSWORD_ERROR("USER_PASSWORD_ERROR"),
	USER_PASSWORD_LENGTH("USER_PASSWORD_LENGTH"),
	USER_ACCEPT_CONDITION("USER_ACCEPT_CONDITION"),
	BET_NOT_ALLOWED("BET_NOT_ALLOWED")
	;
	
	private String value;

    private MessageResourcesNameEnum(String value) {
            this.value = value;
    }
    public String getValue(){
    	return value;
    }
}
