package org.alterq.util.enumeration;

public enum QueueMailEnum {
	Q_DAILYMAIL,Q_RESULTSMAIL,Q_RESULTUSERMAIL,Q_FORGOTMAIL,Q_WITHOUTMONEYMAIL,Q_WITHOUTBETMAIL,Q_BIRTHDAYMAIL,Q_FINALBETMAIL,Q_JOINTOCOMPANYMAIL, Q_CONTACTMAIL
}